vtmarketplace/project/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    
    # vtmarketplace urls containing urls for all apps
    url(r'^', include('vtmarketplace.urls')),
)

# In Debug mode we need to serve media files
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vtmarketplace/vtmarketplace/accounts/urls.py
from django.conf.urls import url

from vtmarketplace.accounts.views import LoginView, LogoutView, RegisterView, ForgotPasswordView, PasswordResetView, ChangePasswordView

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='accounts_login'),
    url(r'^redirect/$', LoginView.as_view(), name='accounts_redirect'),
    url(r'^logout/$', LogoutView.as_view(), name='accounts_logout'),
    url(r'^register/$', RegisterView.as_view(), name='accounts_register'),
    url(r'^forgot_password/$', ForgotPasswordView.as_view(), name='accounts_forgot_password'),
    url(r'^change_password/$', ChangePasswordView.as_view(), name='accounts_change_password'),
    url(r'^password_reset/(?P<user_id>\d+)-(?P<reset_code>\w+)/$',
        PasswordResetView.as_view(), name='accounts_password_reset'),
]

vtmarketplace/vtmarketplace/conf/project_template/project_name/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', '{{ project_name }}.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    
    # vtmarketplace urls containing urls for all apps
    url(r'^', include('vtmarketplace.urls')),
)

# In Debug mode we need to serve media files
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vtmarketplace/vtmarketplace/urls.py
from django.conf.urls import include, url


# vtmarketplace apps urls
urlpatterns = [
    url(r'^', include('vtmarketplace.catalog.urls')),
    url(r'^accounts/', include('vtmarketplace.accounts.urls')),
    url(r'^sales/', include('vtmarketplace.sales.urls')),
    url(r'^payments/', include('vtmarketplace.payments.urls')),
    url(r'^pages/', include('vtmarketplace.pages.urls'))
]

vtmarketplace/vtmarketplace/geo/models.py
from __future__ import unicode_literals

from django.db import models
from django.conf import settings


class Country(models.Model):
    """
    Represents a country
    """
    name = models.CharField(max_length=100, unique=True)
    allow_billing = models.BooleanField(default=True, help_text='Allow billing from this country')
    allow_shipping = models.BooleanField(default=True, help_text='Allow shipping to this country')
    iso_code2 = models.CharField(max_length=2, unique=True, help_text='Two letter ISO code')
    iso_code3 = models.CharField(max_length=3, unique=True, help_text='Three letter ISO code')
    iso_numeric = models.IntegerField(help_text='Numeric ISO code')
    subject_to_vat = models.BooleanField(default=False, help_text='Is VAT applicable')
    display_order = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)
    updated_on = models.DateTimeField(auto_now=True)
    updated_by = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=100)

    class Meta:
        ordering = ('display_order', 'name',)
        verbose_name_plural = 'Countries'

    def __unicode__(self):
        return self.name


class State(models.Model):

    """
    Represents a state
    """
    name = models.CharField(max_length=100, unique=True)
    code = models.CharField(max_length=10, help_text='Abbrevation')
    country = models.ForeignKey(Country)
    is_active = models.BooleanField(default=True)
    display_order = models.IntegerField(default=0)
    updated_on = models.DateTimeField(auto_now=True)
    updated_by = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=100)

    class Meta:
        ordering = ('display_order', 'name',)

    def __unicode__(self):
        return self.name


class Address(models.Model):
    """
    Represents a address for billing and shipping
    """
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    company = models.CharField(max_length=100, null=True, blank=True)
    country = models.ForeignKey(Country, verbose_name='your text')
    state = models.ForeignKey(State, null=True, blank=True)
    city = models.CharField(max_length=100)
    address1 = models.CharField(max_length=250)
    address2 = models.CharField(max_length=250, null=True, blank=True)
    zip_or_postal_code = models.CharField(max_length=10)
    phone_number = models.CharField(max_length=20)
    fax_number = models.CharField(max_length=20, null=True, blank=True)
    updated_on = models.DateTimeField(auto_now=True)
    updated_by = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Addresses'

    def __unicode__(self):
        address = '%s %s %s' % (self.first_name, self.last_name, self.address1)

        if self.address2:
            address += ' ' + self.address2

        address += ', ' + self.city

        if self.state:
            address += ', ' + unicode(self.state)

        if self.country:
            address += ', ' + unicode(self.country)

        return address

    def get_name(self):
        return '%s %s' % (self.first_name, self.last_name)

vtmarketplace/vtmarketplace/accounts/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model


# USER_AUTH_MODEL defined in settings.py
User = get_user_model()


class RegisterForm(forms.ModelForm):

    """
    Customer registration form
    """
    password = forms.CharField(widget=forms.PasswordInput(attrs={'required': ''}),
                               min_length=8, max_length=50,
                               error_messages={'required': 'Please enter your new password.'})
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'required': ''}),
        max_length=50, error_messages={'required': 'Please re-enter your new password for confirmation.'})

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'gender')
        widgets = {
            'username': forms.TextInput(attrs=({'required': ''})),
            'email': forms.EmailInput(attrs=({'required': ''})),
            'first_name': forms.TextInput(attrs=({'required': ''})),
            'last_name': forms.TextInput(attrs=({'required': ''})),
            'gender': forms.RadioSelect(choices=User.GENDERS, attrs=({'required': ''}))
        }
        error_messages = {
            'username': {'required': 'Please choose a username.'},
            'gender': {'required': 'Please specify your gender.'}
        }

    def clean_email(self):
        email = self.cleaned_data['email']

        if not email:
            raise ValidationError('Please enter you email address.')

        if User.objects.filter(email__iexact=email).exists():
            raise ValidationError('User with this email address already exists.')

        return email

    def clean_username(self):
        username = self.cleaned_data['username']

        if '@' in username:
            raise ValidationError('User name shouldn\'t be email address')

        return username

    def clean_first_name(self):
        first_name = self.cleaned_data['first_name']

        if not first_name:
            raise ValidationError('Please enter your first name.')

        return first_name

    def clean_last_name(self):
        last_name = self.cleaned_data['last_name']

        if not last_name:
            raise ValidationError('Please enter your last name.')

        return last_name

    def clean_confirm_password(self):
        confirm_password = self.cleaned_data['confirm_password']
        if 'password' in self.cleaned_data and self.cleaned_data['password'] != confirm_password:
            raise forms.ValidationError("Your new password and confirm password didn't matched.")
        return confirm_password


class PasswordResetForm(forms.Form):
    """
    Password reset form
    """
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'required': ''}), min_length=8, max_length=50,
        error_messages={'required': 'Please enter your new password.'})
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'required': ''}), max_length=50,
        error_messages={'required': 'Please re-enter your new password for confirmation.'})

    def clean_confirm_password(self):
        confirm_password = self.cleaned_data['confirm_password']
        if 'password' in self.cleaned_data and self.cleaned_data['password'] != confirm_password:
            raise forms.ValidationError("Your new password and confirm password didn't matched.")
        return confirm_password


class ChangePasswordForm(PasswordResetForm):
    """
    Change password form
    """
    current_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'required': ''}), max_length=50,
        error_messages={'required': 'Please enter your current password.'})

vtmarketplace/vtmarketplace/accounts/views.py
"""
Accounts views for vtmarketplace apps
"""

from django.db import transaction
from django.conf import settings
from django.http import HttpResponseRedirect
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.contrib.auth import get_user_model, authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.template import Context
from django.template.loader import get_template

from vtmarketplace.views import BaseView
from vtmarketplace.exceptions import vtmarketplaceError
from vtmarketplace.decorators import anonymous_required
from vtmarketplace.catalog.views import CatalogBaseView
from vtmarketplace.accounts.forms import RegisterForm, PasswordResetForm, ChangePasswordForm
from vtmarketplace.utils.helpers import send_mail


User = get_user_model()


class LoginView(CatalogBaseView):
    """
    Login view for vtmarketplace
    """
    template_name = 'accounts/login.html'
    decorators = [anonymous_required]

    def get_context_data(self, **kwargs):
        next_url = self.request.GET.get('next', '')
        return super(LoginView, self).get_context_data(next_url=next_url, **kwargs)

    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']

        if '@' in username:
            try:
                user = User.objects.get(email__iexact=username)
                username = user.username
            except User.DoesNotExist:
                pass

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(request.POST.get('next', reverse('catalog_index')))
            else:
                error = ('Your account has been disabled. We apologize for any inconvenience! If this is a mistake'
                         ' please contact our <a href="mailto:%s">support</a>.') % settings.SUPPORT_EMAIL
        else:
            error = ('Username and password didn\'t matched, if you forgot your password?'
                     ' <a href="%s">Request new one</a>') % reverse('accounts_forgot_password')

        return super(LoginView, self).get(request, error=error)


class LogoutView(BaseView):
    """
    Logout view from vtmarketplace
    """

    def get(self, request):
        logout(request)
        return HttpResponseRedirect(settings.LOGIN_REDIRECT_URL)


class RegisterView(CatalogBaseView):
    """
    User registration view
    """
    page_title = 'Register'
    template_name = "accounts/register.html"
    decorators = [transaction.atomic, anonymous_required]

    def get_context_data(self, **kwargs):
        next_url = self.request.GET.get('next', '')
        return super(RegisterView, self).get_context_data(next_url=next_url, **kwargs)

    def get(self, request):
        form = RegisterForm()
        as_superuser = User.objects.count() == 0
        return super(RegisterView, self).get(request, form=form, as_superuser=as_superuser)

    def post(self, request):
        error = None
        success = None
        form = RegisterForm(request.POST)

        if form.is_valid():
            try:
                data = form.cleaned_data
                User.objects.register(data['first_name'], data['last_name'], data['email'],
                                      data['gender'], data['username'], data['password'])

                # Login registered user automatically
                # Binding propery backend to user model
                user = authenticate(username=data['username'], password=data['password'])
                login(request, user)

                next_url = request.POST.get('next', None)
                if next_url:
                    return HttpResponseRedirect(next_url)

                success = 'Thank you for sign up, you have been also successfully logged in, <strong>lets explore!</strong>'
            except ValidationError as e:
                error = e.message

        return super(RegisterView, self).get(request, form=form, error=error, success=success)


class ForgotPasswordView(CatalogBaseView):
    """
    Password recovery view
    """
    template_name = 'accounts/forgot_password.html'
    decorators = [anonymous_required]
    page_title = 'Forgot password'

    def post(self, request):
        error = None
        success = None
        email = request.POST.get('email', None)

        if email:
            email = email.strip()
            try:
                user = User.objects.get_reset_code(email)

                # Sending password reset link email to user
                context = Context({'user': user, 'SITE_NAME': 'VTMarketPlace', 'DOMAIN': self.get_config('DOMAIN')})
                msg_subject = get_template("accounts/email/password_reset_subject.txt").render(context)
                context = Context({'user': user, 'SITE_NAME': 'VTMarketPlace', 'DOMAIN': self.get_config('DOMAIN')})
                msg_text = get_template("accounts/email/password_reset.html").render(context)
                to_email = '%s <%s>' % (user.get_full_name(), user.email)
                send_mail(msg_subject, msg_text, [to_email], True)

                success = 'Password reset intructions has been sent to your email address.'
            except vtmarketplaceError as e:
                error = e.message

        return self.get(request, error=error, success=success)


class PasswordResetView(CatalogBaseView):
    """
    Password recovery view
    """
    page_title = 'Password reset'
    template_name = 'accounts/password_reset.html'
    decorators = [anonymous_required]

    def get(self, request, user_id, reset_code):
        form = PasswordResetForm()
        return super(PasswordResetView, self).get(request, form=form, user_id=user_id, reset_code=reset_code)

    def post(self, request, user_id, reset_code):
        error = None
        success = None
        form = PasswordResetForm(request.POST)

        if form.is_valid():
            data = form.cleaned_data
            try:
                User.objects.reset_password(user_id, reset_code, data['password'])
                success = 'Your password has been successfully reset!'
            except vtmarketplaceError as e:
                error = e.message

        return super(PasswordResetView, self).get(request, form=form, user_id=user_id, reset_code=reset_code,
                                                  error=error, success=success)


class ChangePasswordView(CatalogBaseView):
    """
    Password recovery view
    """
    page_title = 'Change password'
    template_name = 'accounts/change_password.html'
    decorators = [login_required]

    def get(self, request):
        form = ChangePasswordForm()
        return super(ChangePasswordView, self).get(request, form=form)

    def post(self, request):
        error = None
        success = None
        form = ChangePasswordForm(request.POST)

        if form.is_valid():
            data = form.cleaned_data
            try:
                User.objects.change_password(request.user, data['current_password'], data['password'])
                success = 'Your password has been successfully changed!'
            except vtmarketplaceError as e:
                error = e.message

        return super(ChangePasswordView, self).get(request, form=form, error=error, success=success)

vtmarketplace/vtmarketplace/accounts/templates/accounts/change_password.html
{% extends "catalog/catalog_base.html" %}

{% block catalog-content %}
<div class="row no-gutters">
	<div class="card bg-light col-md-8 offset-md-2 col-lg-6 offset-lg-3">
		<div class="card-header">Change your password</div>
		{% if success %}
		<div class="card-body">
			<p class="text-success">{{ success|safe }}</p>
		</div>
		{% else %}
		<form method="post" action="{% url 'accounts_change_password' %}">
			{% csrf_token %}
			<div class="card-body">
				{% if error %}
				<p class="text-danger">
					{{ error|safe }}
				</p>
				{% endif %}
				<div class="form-group">
					<input id="{{ form.current_password.id_for_label }}" name="{{ form.current_password.name }}" type="password" class="form-control {% if form.current_password.errors %}is-invalid{% endif %}" placeholder="Current password" required="" />
					{% if form.current_password.errors %}
					<div class="invalid-feedback">
						{{ form.current_password.errors|first|safe }}
					</div>
					{% endif %}
				</div>
				<div class="form-row">
					<div class="col-sm-12 col-md-6 form-group">
						<input id="{{ form.password.id_for_label }}" name="{{ form.password.name }}" type="password" class="form-control {% if form.password.errors %}is-invalid{% endif %}" placeholder="New password" required="" />
						{% if form.password.errors %}
						<div class="invalid-feedback">
							{{ form.password.errors|first|safe }}
						</div>
						{% endif %}
					</div>
					<div class="col-sm-12 col-md-6 form-group">
						<input id="{{ form.confirm_password.id_for_label }}" name="{{ form.confirm_password.name }}" type="password" class="form-control {% if form.confirm_password.errors %}is-invalid{% endif %}" placeholder="Confirm password" required="" />
						{% if form.confirm_password.errors %}
						<div class="invalid-feedback">
							{{ form.confirm_password.errors|first|safe }}
						</div>
						{% endif %}
					</div>
			  </div>
				<div class="text-right">
					<button class="btn btn-primary"><i class="fas fa-lock mr-2"></i>Change password</button>
				</div>
			</div>
		</form>
		{% endif %}
	</div>
</div>
{% endblock %}

vtmarketplace/vtmarketplace/accounts/templates/accounts/forgot_password.html
{% extends "catalog/catalog_base.html" %} {% block catalog-content %}
<div class="row no-gutters">
	<div class="card bg-light col-md-8 offset-md-2 col-lg-6 offset-lg-3">
		<div class="card-header">Forgot your password?</div>
		{% if success %}
		<div class="card-body">
			<p class="text-success">{{ success|safe }}</p>
		</div>
		{% else %}
		<form method="post" action="{% url 'accounts_forgot_password' %}">
			{% csrf_token %}
			<input type="hidden" name="next" value="{{ next_url }}" />
			<div class="card-body">
				<div class="form-group">
					<input id="id_email" name="email" type="email" value="{{ email }}" class="form-control {% if error %}is-invalid{% endif %}" placeholder="Email" required="" />
					{% if error %}
					<div class="invalid-feedback">
						{{ error|safe }}
					</div>
					{% endif %}
				</div>
				<div>
					<a href="{% url 'accounts_login' %}" class="card-link" data-toggle="tooltip" data-tooltip="Log In to our shop and explore quickly">Log In</a>
					<a href="{% url 'accounts_register' %}" class="card-link" data-toggle="tooltip" data-tooltip="Sign Up to our shop faster and better!">Sign Up</a>
					<div class="text-right"><button class="btn btn-primary"><i class="fas fa-link mr-2"></i>Request password reset</button>
					</div>
				</div>
			</div>
		</form>
		{% endif %}
	</div>
</div>
{% endblock %}

vtmarketplace/vtmarketplace/accounts/templates/accounts/login.html
{% extends "catalog/catalog_base.html" %}

{% block catalog-content %}
<div class="row no-gutters">
	<div class="card bg-light col-md-8 offset-md-2 col-lg-6 offset-lg-3">
		<div class="card-header">Log In</div>
		<form method="post" action="{% url 'accounts_login' %}">
			{% csrf_token %}
			<input type="hidden" name="next" value="{{ next_url }}" />
		
			<div class="card-body">
				{% if error %}
				<p class="text-danger">
					{{ error|safe }}
				</p>
				{% endif %}
				<div class="form-group">
					<input id="id_username" name="username" type="text" value="{{ username }}" required="" class="form-control" placeholder="Username or email" />
				</div>
				<div class="form-group">
					<input id="id_password" name="password" type="password" class="form-control" placeholder="Password">
				</div>
				<div>
					<a href="{% url 'accounts_register' %}{% if next_url %}?next={{ next_url|urlencode }}{% endif %}" class="card-link" data-toggle="tooltip" title="Register to shop faster and better!">Register</a>
					<a href="{% url 'accounts_forgot_password' %}" class="card-link" data-toggle="tooltip" title="Request new password">Forgot your password?</a>
					<div class="text-right">
						<button class="btn btn-secondary"><i class="fas fa-lock mr-2"></i>Log In</button>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>
{% endblock %}

vtmarketplace/vtmarketplace/accounts/templates/accounts/password_reset.html
{% extends "catalog/catalog_base.html" %} {% block catalog-content %}
<div class="row no-gutters">
	<div class="card bg-light col-md-8 offset-md-2 col-lg-6 offset-lg-3">
		<div class="card-header">Password reset</div>
		{% if success %}
		<div class="card-body">
			<p class="text-success">{{ success|safe }}</p>
		</div>
		{% else %}
		<form method="post" action="{% url 'accounts_password_reset' user_id reset_code %}">
			{% csrf_token %}
			<input type="hidden" name="next" value="{{ next_url }}" />
			<div class="card-body">
				{% if error %}
				<p class="text-danger">
					{{ error|safe }}
				</p>
				{% endif %}
				<div class="form-group">
					<input id="{{ form.password.id_for_label }}" name="{{ form.password.name }}" type="password" class="form-control {% if form.password.errors %}is-invalid{% endif %}" placeholder="New password" required="" />
					{% if form.password.errors %}
					<div class="invalid-feedback">
						{{ form.password.errors|first|safe }}
					</div>
					{% endif %}
				</div>
				<div class="form-group">
					<input id="{{ form.confirm_password.id_for_label }}" name="{{ form.confirm_password.name }}" type="password" class="form-control {% if form.confirm_password.errors %}is-invalid{% endif %}" placeholder="Confirm password" required="" />
					{% if form.confirm_password.errors %}
					<div class="invalid-feedback">
						{{ form.confirm_password.errors|first|safe }}
					</div>
					{% endif %}
				</div>
				<div class="text-right">
					<button class="btn btn-primary"><i class="fas fa-link mr-2"></i>Save new password</button>
				</div>
			</div>
		</form>
		{% endif %}
	</div>
</div>
{% endblock %}

vtmarketplace/vtmarketplace/accounts/templates/accounts/redirect.html
<html>

<head></head>
<body>Hello Welcome !!!</body>
    </html>

vtmarketplace/vtmarketplace/accounts/templates/accounts/register.html
{% extends "catalog/catalog_base.html" %}

{% block catalog-content %}
<div class="row no-gutters">
	<div class="card bg-light col-md-8 offset-md-2 col-lg-6 offset-lg-3">
		<div class="card-header">Sign Up</div>
		{% if success %}
		<div class="card-body">
			<p class="text-success">{{ success|safe }}</p>
		</div>
		{% else %}
		<form method="post" action="{% url 'accounts_register' %}">
			{% csrf_token %}
			<input type="hidden" name="next" value="{{ next_url }}" />
			<div class="card-body">
				{% if as_superuser %}
				<p class="text-info">
						Sign Up yourself as site administrator, you will have all permissions on this site.
				</p>
				{% endif %}
				{% if error %}
				<p class="text-danger">
					{{ error|safe }}
				</p>
				{% endif %}
				<div class="form-row">
					<div class="col-sm-12 col-md-6 form-group">
						<input id="{{ form.first_name.id_for_label }}" name="{{ form.first_name.name }}" type="text" class="form-control {% if form.first_name.errors %}is-invalid{% endif %}" placeholder="First name" required="" value="{{ form.first_name.value|default:'' }}" />
						{% if form.first_name.errors %}
						<div class="invalid-feedback">
							{{ form.first_name.errors|first|safe }}
						</div>
						{% endif %}
					</div>
					<div class="col-sm-12 col-md-6 form-group">
						<input id="{{ form.last_name.id_for_label }}" name="{{ form.last_name.name }}" type="text" class="form-control {% if form.last_name.errors %}is-invalid{% endif %}" placeholder="Last name" required=""  value="{{ form.last_name.value|default:'' }}" />
						{% if form.last_name.errors %}
						<div class="invalid-feedback">
							{{ form.last_name.errors|first|safe }}
						</div>
						{% endif %}
					</div>
			  </div>
				<div class="form-row">
					<div class="col-sm-12 col-md-6 form-group">
						<input id="{{ form.email.id_for_label }}" name="{{ form.email.name }}" type="email" class="form-control {% if form.email.errors %}is-invalid{% endif %}" placeholder="Email" required=""  value="{{ form.email.value|default:'' }}" />
						{% if form.email.errors %}
						<div class="invalid-feedback">
							{{ form.email.errors|first|safe }}
						</div>
						{% endif %}
					</div>
					<div class="col-sm-12 col-md-6 form-group">
						<div class="input-group">
			        <div class="input-group-prepend">
			          <div class="input-group-text">@</div>
			        </div>
			        <input id="{{ form.username.id_for_label }}" name="{{ form.username.name }}" type="text" class="form-control {% if form.username.errors %}is-invalid{% endif %}" placeholder="Username" required=""  value="{{ form.username.value|default:'' }}" />
							{% if form.username.errors %}
							<div class="invalid-feedback">
								{{ form.username.errors|first|safe }}
							</div>
							{% endif %}
			      </div>
					</div>
				</div>
				<div class="form-row">
					<div class="col-sm-12 col-md-6 form-group">
						<input id="{{ form.password.id_for_label }}" name="{{ form.password.name }}" type="password" class="form-control {% if form.password.errors %}is-invalid{% endif %}" placeholder="New password" required="" />
						{% if form.password.errors %}
						<div class="invalid-feedback">
							{{ form.password.errors|first|safe }}
						</div>
						{% endif %}
					</div>
					<div class="col-sm-12 col-md-6 form-group">
						<input id="{{ form.confirm_password.id_for_label }}" name="{{ form.confirm_password.name }}" type="password" class="form-control {% if form.confirm_password.errors %}is-invalid{% endif %}" placeholder="Confirm password" required="" />
						{% if form.confirm_password.errors %}
						<div class="invalid-feedback">
							{{ form.confirm_password.errors|first|safe }}
						</div>
						{% endif %}
					</div>
			  </div>
				<div class="pl-1">
					{% for choice in form.gender.field.choices %}
					<div class="custom-control custom-radio custom-control-inline">
						<input type="radio" id="{{ form.gender.id_for_label}}_{{ choice.0 }}" name="{{ form.gender.name }}" class="custom-control-input" required="" value="{{ choice.0 }}" {% if choice.0 == form.gender.data %}checked="checked" {% endif %}>
						<label class="custom-control-label" for="{{ form.gender.id_for_label}}_{{ choice.0 }}">{{ choice.1 }}</label>
					</div>
					{% endfor %}
				</div>
				<div class="text-right">
					<button class="btn btn-primary"><i class="fas fa-user-plus mr-2"></i>Sign Up</button>
				</div>
			</div>
		</form>
		{% endif %}
	</div>
</div>
{% endblock %}