vtmarketplace/project/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    
    # vtmarketplace urls containing urls for all apps
    url(r'^', include('vtmarketplace.urls')),
)

# In Debug mode we need to serve media files
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vtmarketplace/vtmarketplace/conf/project_template/project_name/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', '{{ project_name }}.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    
    # vtmarketplace urls containing urls for all apps
    url(r'^', include('vtmarketplace.urls')),
)

# In Debug mode we need to serve media files
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vtmarketplace/vtmarketplace/payments/urls.py
from django.conf.urls import url

from vtmarketplace.payments.views import process_online, process_credit_card, \
    process_account_request, process_account_response, ProcessingMessageView

urlpatterns = [
    url(r'^process_online/(?P<order_id>\d+)-(?P<receipt_code>\w+)/$',
        process_online, name='payments_process_online'),
    url(r'^process_credit_card/(?P<order_id>\d+)-(?P<receipt_code>\w+)/$',
        process_credit_card, name='payments_process_credit_card'),
    url(r'^process_account/request/(?P<order_id>\d+)-(?P<receipt_code>\w+)/$',
        process_account_request, name='payments_process_account_request'),
    url(r'^process_account/success/(?P<transaction_id>\d+)-(?P<access_token>\w+)/$',
        process_account_response, {'success': True}, name='payments_process_account_success'),
    url(r'^process_account/cancel/(?P<transaction_id>\d+)-(?P<access_token>\w+)/$',
        process_account_response, {'success': False}, name='payments_process_account_cancel'),
    url(r'^processing_message/$', ProcessingMessageView.as_view(),
        name='payments_processing_message'),
]

vtmarketplace/vtmarketplace/urls.py
from django.conf.urls import include, url


# vtmarketplace apps urls
urlpatterns = [
    url(r'^', include('vtmarketplace.catalog.urls')),
    url(r'^accounts/', include('vtmarketplace.accounts.urls')),
    url(r'^sales/', include('vtmarketplace.sales.urls')),
    url(r'^payments/', include('vtmarketplace.payments.urls')),
    url(r'^pages/', include('vtmarketplace.pages.urls'))
]

vtmarketplace/vtmarketplace/models.py
from __future__ import unicode_literals

from django.db import models
from django.core.exceptions import ImproperlyConfigured


class SysConfig(models.Model):
    """
    System configuration parameters class

    Configuration paramters such as Page Size, Support Email and etc... will be store in database
    """

    name = models.CharField(max_length=100, unique=True)
    value = models.CharField(max_length=250, blank=True)
    description = models.CharField(max_length=500)
    updated_on = models.DateTimeField(auto_now=True)
    updated_by = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=100)

    class Meta:
        db_table = 'vtmarketplace_sys_config'
        verbose_name = 'System Config'
        verbose_name_plural = 'System Configs'
        ordering = ['id']

    @classmethod
    def get_config(cls, name):
        """
        Returns System Configuration value defined in database against name
        """
        sys_configs = SysConfig.get_configs()
        if name in sys_configs:
            return sys_configs[name]

        raise ImproperlyConfigured('"%s" does not found, it should be defined it in System Configs' % name)

    @classmethod
    def get_configs(cls):
        """
        Returns System Configs dictionary from database

        Configurations will be loaded when first time demanded
        """
        if not hasattr(cls, 'sys_configs'):
            cls.sys_configs = dict((sys_config.name, sys_config.value) for sys_config in cls.objects.all())

        return cls.sys_configs

vtmarketplace/vtmarketplace/payments/forms.py
import re
import datetime

from django import forms

from vtmarketplace.payments.models import Gateway


class CreditCardForm(forms.Form):
    """
    Credit card payment form
    """
    REGEX_EXPIRY = re.compile(r'^(\d{2})\s/\s(\d{2})$')
    REGEX_CVV2 = re.compile(r'^(\d{3,4})$')

    gateway = forms.ModelChoiceField(queryset=Gateway.objects.filter(is_active=True, accept_credit_card=True),
                                     empty_label=None, widget=forms.HiddenInput())
    card_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder': 'Name...'}),
                                error_messages={'required': 'Please specify name on credit card.'})
    card_number = forms.CharField(max_length=24, widget=forms.TextInput(attrs={'placeholder': 'Number...'}),
                                  error_messages={'required': 'Please specify credit card number.'})
    card_type = forms.CharField(widget=forms.HiddenInput(), required=False)
    expire_date = forms.CharField(max_length=7, widget=forms.TextInput(attrs={'placeholder': 'MM / YY'}),
                                  error_messages={'required': 'Please specify card expiry date'})
    cvv2 = forms.CharField(max_length=4, widget=forms.TextInput(attrs={'placeholder': 'CVV2...'}),
                           error_messages={'required': 'Please specify card security code'})

    def clean_card_number(self):
        card_number = self.cleaned_data['card_number'].replace(' ', '')
        try:
            int(card_number)
        except ValueError:
            raise forms.ValidationError("Please specify correct card number.")

        return card_number

    def clean_card_type(self):
        card_type = self.cleaned_data.get('card_type', None)
        card_number = self.cleaned_data.get('card_number', None)

        if card_number and not card_type:
            raise forms.ValidationError('We can\'t recognize your card issuer type.')

        return card_type

    def clean_expire_date(self):
        expire_date = self.cleaned_data['expire_date']
        match = self.REGEX_EXPIRY.search(expire_date)

        if match:
            month, year = match.groups()
            try:
                expire_date = datetime.date(2000 + int(year), int(month), 1)
                if expire_date > datetime.date.today():
                    return expire_date
                else:
                    raise forms.ValidationError("Card expiry date has already been passed.")
            except ValueError:
                pass

        raise forms.ValidationError("Please specify correct card expiry date.")

    def clean_cvv2(self):
        cvv2 = self.cleaned_data['cvv2']

        if not self.REGEX_CVV2.search(cvv2):
            raise forms.ValidationError("Please specify correct card security code.")

        return cvv2

    def clean(self):
        cleaned_data = super(CreditCardForm, self).clean()

        if ('card_name' in cleaned_data and 'card_number' in cleaned_data and
                'card_type' in cleaned_data and 'expire_date' in cleaned_data and 'cvv2' in cleaned_data):

            card_name = cleaned_data['card_name']
            expire_date = cleaned_data['expire_date']

            cleaned_data['card'] = {
                'number': cleaned_data['card_number'],
                'type': cleaned_data['card_type'],
                'cvv2': cleaned_data['cvv2'],
                'name': card_name,
                'first_name': card_name.split(' ')[0],
                'last_name': ' '.join(card_name.split(' ')[1:]),
                'expire_month': str(expire_date.month),
                'expire_year': str(expire_date.year)
            }

        return cleaned_data

vtmarketplace/vtmarketplace/payments/views.py
from django.db import transaction
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.core.exceptions import ImproperlyConfigured
from django.core.urlresolvers import reverse

from vtmarketplace.exceptions import vtmarketplaceError
from vtmarketplace.sales.models import Order
from vtmarketplace.catalog.views import CatalogBaseView, get_default_currency
from vtmarketplace.payments.forms import CreditCardForm
from vtmarketplace.payments.models import Gateway, Transaction, TransactionParam
from vtmarketplace.payments.processors import PayPal, Stripe


def process_online(request, order_id, receipt_code):
    """
    Shows online or process online payment
    """
    if request.method == 'GET':
        form = None
        gateways = Gateway.get_gateways()
        order = get_object_or_404(Order, id=order_id, receipt_code=receipt_code)
        default_currency = get_default_currency(request)

        for gateway in gateways:
            if gateway.accept_credit_card:
                form = CreditCardForm(initial={'gateway': gateway})

        return render(request, 'payments/process_online.html',
                      {'form': form, 'order': order, 'gateways': gateways, 'default_currency': default_currency})

    raise Http404


@transaction.non_atomic_requests
def process_credit_card(request, order_id, receipt_code):
    """
    Process credit card payment
    """
    if request.method == 'POST':
        error = None
        form = CreditCardForm(request.POST)
        order = get_object_or_404(Order, id=order_id, receipt_code=receipt_code)

        if form.is_valid():
            data = form.cleaned_data
            gateway = data['gateway']

            if gateway.name == Gateway.PAYPAL:
                processor = PayPal(gateway)
            elif gateway.name == Gateway.STRIPE:
                processor = Stripe(gateway)
            else:
                raise ImproperlyConfigured('%s is not supported gateway for processing credit cards.' % gateway)

            try:
                processor.credit_card_payment(data['card'], order, request.user)
                return render(request, 'payments/credit_card_processed.html', {'order': order})
            except vtmarketplaceError as e:
                error = e.message

        gateways = Gateway.get_gateways()
        default_currency = get_default_currency(request)
        return render(request, 'payments/process_online.html',
                      {'form': form, 'order': order, 'gateways': gateways,
                       'default_currency': default_currency, 'error': error})

    raise Http404


@transaction.non_atomic_requests
def process_account_request(request, order_id, receipt_code):
    """
    Process payment via online account like PayPal, Amazon ...etc
    """
    order = get_object_or_404(Order, id=order_id, receipt_code=receipt_code)
    if request.method == "POST":
        gateway_name = request.POST["gateway_name"]
        gateway = get_object_or_404(Gateway, name=gateway_name)

        try:
            if gateway.name == Gateway.PAYPAL:
                processor = PayPal(gateway)
                return HttpResponseRedirect(processor.create_account_payment(order, request.user))
            else:
                raise ImproperlyConfigured('vtmarketplace doesn\'t yet support payment with %s account.'
                                           % gateway.get_name_display())
        except vtmarketplaceError as e:
            request.session['processing_error'] = e.message
            return HttpResponseRedirect(reverse('payments_processing_message'))

    raise Http404


@transaction.non_atomic_requests
def process_account_response(request, transaction_id, access_token, success):
    """
    Process payment via online account like PayPal, Amazon ...etc
    """
    payment_txn = get_object_or_404(Transaction, id=int(transaction_id))
    try:
        if payment_txn.get_param('access_token') != access_token:
            raise Http404
    except TransactionParam.DoesNotExist:
        raise Http404

    if request.method == "GET":
        order = payment_txn.order
        gateway = payment_txn.gateway

        try:
            if gateway.name == Gateway.PAYPAL:
                processor = PayPal(gateway)
                if success:
                    payer_id = request.GET['PayerID']
                    processor.execute_account_payment(payer_id, payment_txn, request.user)
                    return HttpResponseRedirect(reverse('sales_checkout_receipt', args=[order.id, order.receipt_code]))
                else:
                    processor.cancel_account_payment(payment_txn, request.user)
                    request.session['processing_message'] = 'Your order has been canceled.'
                    return HttpResponseRedirect(reverse('payments_processing_message'))
            else:
                raise ImproperlyConfigured('vtmarketplace doesn\'t yet support payment with %s account.'
                                           % gateway.get_name_display())

        except vtmarketplaceError as e:
            request.session['processing_error'] = e.message
            return HttpResponseRedirect(reverse('payments_processing_message'))

    raise Http404


class ProcessingMessageView(CatalogBaseView):
    """
    Shows payment processing message or error
    """
    template_name = 'payments/processing_message.html'

    def get(self, request):
        breadcrumbs = ({'name': 'Processing Status', 'url': reverse('payments_processing_message')},)

        if 'processing_error' in request.session:
            return super(ProcessingMessageView, self).get(
                request, error=request.session.pop('processing_error'), breadcrumbs=breadcrumbs)
        elif 'processing_message' in request.session:
            return super(ProcessingMessageView, self).get(
                request, message=request.session.pop('processing_message'), breadcrumbs=breadcrumbs)

        return HttpResponseRedirect(reverse('sales_checkout_cart'))

vtmarketplace/vtmarketplace/payments/templates/payments/credit_card_processed.html
<div class="modal-dialog modal-lg modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Payment processing</h5>
      </div>
      <div class="modal-body">
        <p class="text-success">
            <i class="fa fa-credit-card mr-2"></i>
            Your credit card has been processed successfully. redirecting<span id="dots" class="text"></span>
        </p>
        <p>
          <a id="a-order-receipt" class="d-none" href="{% url 'sales_checkout_receipt' order.id order.receipt_code %}">View your order receipt here...</a>
        </p>
      </div>
    </div>
</div>

<script type="text/javascript">
    setTimeout(function(){
        $('#a-order-receipt').fadeIn(1000);
        window.location = $('#a-order-receipt').attr('href');
    }, 3000);

    setInterval(aniDots, 600);
    function aniDots() {
        if(dots < 3) {
            $('#dots').append('.');
            dots++;
        } else {
            $('#dots').html('');
            dots = 0;
        }
    }
</script>

vtmarketplace/vtmarketplace/payments/templates/payments/process_online.html
{% load catalog_filters %}
<div id="payment-options" class="modal-dialog modal-dialog-centered" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">Payment processing</h5>
    </div>
    <div class="modal-body">
      <ul class="nav nav-pills justify-content-center">
        {% if form %}
        <li class="nav-item">
          <a id="tab-credit-card" class="nav-link active" href="#tab-content-credit-card" data-toggle="tab" role="tab" aria-controls="tab-content-credit-card" aria-selected="true">Credit Card</a>
        </li>
        {% endif %}
        {% for gateway in gateways %}
        {% if gateway.accept_account %}
        <li class="nav-item">
          <a class="nav-link" href="#tab-content-payment-{{ gateway.get_name_display }}" data-toggle="tab" role="tab" aria-controls="tab-content-payment-{{ gateway.get_name_display }}" aria-selected="false">{{ gateway.get_name_display }}</a>
        </li>
        {% endif %}
        {% endfor %}
      </ul>
      <div class="tab-content py-5" id="tab-payment-contents">
        <div class="tab-pane fade show active" id="tab-content-credit-card" role="tabpanel" aria-labelledby="tab-credit-card">
          {% if error %}
          <div class="text-danger">
            {{ error }}
          </div>
          {% endif %}
          <form method="post" data-ajax="true" action="{% url 'payments_process_credit_card' order.id order.receipt_code %}" data-ajax-update="#payment-options-container" data-ajax-loading="#process-credit-card">
            {% csrf_token %}
            {{ form.gateway }}
            {{ form.card_type }}
            <div class="form-group">
              <label for="{{ form.card_name.id_for_label }}"><i class="fa fa-user mr-2"></i>Card name</label>
              <input class="form-control {% if form.card_name.errors %}is-invalid{% endif %}" type="text" name="{{ form.card_name.name }}" id="{{ form.card_name.id_for_label }}"  placeholder="Name.." required="" value="{{ form.card_name.value|default:'' }}">
              {% if form.card_name.errors %}
              <div class="invalid-feedback">
              {{ form.card_name.errors|first }}
              </div>
              {% endif %}
            </div>
            <div class="form-group">
              <label for="{{ form.card_number.id_for_label }}"><i class="fa fa-credit-card mr-2"></i>Card number<i class="fas fa-check ml-2 text-success" style="display: none"></i></label>
              <input class="form-control {% if form.card_number.errors %}is-invalid{% endif %}" type="text" name="{{ form.card_number.name }}" id="{{ form.card_number.id_for_label }}"  placeholder="Number.." required="" value="{{ form.card_number.value|default:'' }}">
              {% if form.card_number.errors or form.card_type.errors %}
              <div class="invalid-feedback">
              {{ form.card_number.errors|first }}
              {{ form.card_type.errors|first }}
              </div>
              {% endif %}
            </div>
            <div class="form-row">
              <div class="col-md-6 form-group">
                <label for="{{ form.expire_date.id_for_label }}"><i class="fa fa-calendar-alt mr-2"></i>Expiry date</label>
                <input class="form-control {% if form.expire_date.errors %}is-invalid{% endif %}" type="text" name="{{ form.expire_date.name }}" id="{{ form.expire_date.id_for_label }}" required="" value="{{ form.expire_date.value|default:'' }}">
                {% if form.expire_date.errors %}
                <div class="invalid-feedback">
                {{ form.expire_date.errors|first }}
                </div>
                {% endif %}
              </div>
              <div class="col-md-6 form-group">
                <label for="{{ form.cvv2.id_for_label }}"><i class="fa fa-lock mr-2"></i>CVV2</label>
                <input class="form-control {% if form.cvv2.errors %}is-invalid{% endif %}" type="text" name="{{ form.cvv2.name }}" id="{{ form.cvv2.id_for_label }}"  placeholder="CVV2.." required="" value="{{ form.cvv2.value|default:'' }}">
                {% if form.cvv2.errors %}
                <div class="invalid-feedback">
                {{ form.cvv2.errors|first }}
                </div>
                {% endif %}
              </div>
            </div>
            <div class="form-group text-center mt-5">
              <button class="btn btn-primary" onclick="javascript:$(this).attr('disabled','disabled');" type="submit">
                <i class="fas fa-money-bill-alt mr-2"></i>
                Pay {{ order.total|currency:default_currency }}
              </button>
            </div>
          </form>
        </div>
        {% for gateway in gateways %}
        {% if gateway.accept_account %}
        <div class="tab-pane fade" id="tab-content-payment-{{ gateway.get_name_display }}" role="tabpanel">
            <form method="post" action="{% url 'payments_process_account_request' order.id order.receipt_code %}">
                {% csrf_token %}
                <input type="hidden" name="gateway_name" value="{{ gateway.name }}"/>
                <p class="text-info text-center">
                  Check out with your existing {{ gateway.get_name_display }} account.
                </p>
                <div class="text-center mt-5">
                  <button class="btn btn-primary" type="submit">
                    <i class="fas fa-money-bill-alt mr-2"></i>Pay {{ order.total|currency:default_currency }}
                  </button>
                </div>
            </form>
        </div>
        {% endif %}
        {% endfor %}
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
    // Detect Credit Card Type by Card Number and
    // fills appropiate type automatically in Card Type
    var $cardNumber = $('#id_card_number')
    $cardNumber.change(function(){
        $cardNumber.validateCreditCard(function(result){
            $('#id_card_type').val('');
            $('#payment-options i.fa-check').hide();

            // Removed error highlight if user corrected his card number
            if($cardNumber.hasClass('is-invalid') && result.length_valid && result.luhn_valid)
                $cardNumber.removeClass('is-invalid');

            if(result.card_type) {
                $('#id_card_type').val(result.card_type.name);
                $('#payment-options .fa-check').css('display', 'inline-block');

                // Highlight card number if wrong when user done with entering
                if(!$cardNumber.is(':focus') && (!result.length_valid || !result.luhn_valid))
                    $cardNumber.addClass('is-invalid');
            }
        });
    });

    // Initializing new forms in payment options for ajax requests
    bootstrapAjax($, '#payment-options');

    // Masking inforce correct inputs
    $.mask.definitions['0']='[01]';

    $('#id_card_number').mask('9999 9999 9999 9999? 9999', {placeholder: ' '});
    $('#id_expire_date').mask('09 / 99', {placeholder: '_'});
    $('#id_cvv2').mask('999?9', {placeholder: ' '});
</script>

vtmarketplace/vtmarketplace/payments/templates/payments/processing_message.html
{% extends catalog_template_name %}

{% block catalog-content %}
<div>
    <h3>Payment transaction</h3>
    {% if error %}
    <div class="text-danger mt-5">
      {{ error }}
    </div>
    {% else %}
    <div class="text-info mt-5">
      {{ message }}
    </div>
    {% endif %}
</div>
{% endblock %}